config/routes.rb
Rails.application.routes.draw do

  get 'users/show', to: 'users#show', as: "show_user"
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'review', to: 'checkout#review', as: 'checkout_review'
  end 

  resources :pokemons, only: %i[index show]
  resources :types, only: %i[index show]
  resources :orders, only: %i[index show]
  post 'pokemons/add_to_cart/:id', to: 'pokemons#add_to_cart', as: 'add_to_cart'
  delete 'pokemons/remove_from_cart/:id', to: 'pokemons#remove_from_cart', as: 'remove_from_cart'
  post 'pokemons/modify_cart_quantity', to: 'pokemons#modify_cart_quantity', as: 'modify_cart_quantity'

  get "about", to: "static_pages#about"
  get "contactus", to: "static_pages#contactus"

  # Search Results
  # get "search/results"
  get "search_results", to: "search#results"

  # Home Page
  root to: "pokemons#index"
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :pokemon_types
  has_many :types, through: :pokemon_types

  has_many :pokemon_orders
  has_many :orders, through: :pokemon_orders

  has_one_attached :pokemon_image

  validates :name, :pokedex_number, :price, :quantity, presence: true
  validates :name, :pokedex_number, uniqueness: true
  validates :pokedex_number, :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :price, :sale_percentage, numericality: true
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
  belongs_to :pokemon
  belongs_to :type
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  
  def index
    @pokemons = Pokemon.order(:pokedex_number).page(params[:page]).per(20)
  end

  def show
    @pokemon = Pokemon.find(params[:id])
  end

  def add_to_cart
    id = params[:id].to_i
    
    if session[:cart].any? { |p| p["id"] == id }
      session[:cart][session[:cart].index { |p| p["id"] == id }]["qty"] += 1
    else
      session[:cart] << {"id" => id, "qty" => 1} 
    end 

    redirect_to root_path
  end

  def modify_cart_quantity
    id = params[:pokemon_id].to_i
    new_quantity = params[:quantity].to_i
    if new_quantity == 0
      session[:cart].delete_at(session[:cart].index { |p| p["id"] == id })
    else
      session[:cart][session[:cart].index { |p| p["id"] == id }]["qty"] = new_quantity
    end
    redirect_to root_path
  end

  def remove_from_cart
    id = params[:id].to_i
    session[:cart].delete_at(session[:cart].index { |p| p["id"] == id })
    redirect_to root_path
  end
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/pokemons/_pokemon.html.erb
<img src="<%= pokemon.pokemon_image.present? ? url_for(pokemon.pokemon_image) : pokemon.image %>" alt="Image of <%= pokemon.name %>" width="65">
<h3><%= link_to pokemon.name, pokemon %></h3>
<p>$<%= pokemon.price %></p>
<p><%= link_to 'Add to cart', add_to_cart_path(pokemon.id), data: { "turbo-method": :post } %></p>

app/views/pokemons/index.html.erb
<h1>Pokemons</h1>

<ul>
    <%= render @pokemons %>
    <%= paginate @pokemons %>
</ul>

app/views/pokemons/show.html.erb
<h1><%= @pokemon.name %></h1>

<img src="<%= @pokemon.pokemon_image.present? ? url_for(@pokemon.pokemon_image) : @pokemon.image %>" alt="Image of <%= @pokemon.name %>" width="100">

<ul>
    <li>Pokedex Number: <%= @pokemon.pokedex_number %></li>
    <li>Types:
    <% @pokemon.types.each do |type|%>
        <%= link_to type.name.capitalize, type %>,
    <% end %>
    </li>
    <li>Price: $<%= @pokemon.price %></li>
    <li>Quantity: <%= @pokemon.quantity %> pokemons left</li>
</ul>

<p><%= @pokemon.description %></p>