config/routes.rb
Rails.application.routes.draw do

  get 'users/show', to: 'users#show', as: "show_user"
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  
  scope '/checkout' do
    post 'create', to: 'checkout#create', as: 'checkout_create'
    get 'cancel', to: 'checkout#cancel', as: 'checkout_cancel'
    get 'success', to: 'checkout#success', as: 'checkout_success'
    get 'review', to: 'checkout#review', as: 'checkout_review'
  end 

  resources :pokemons, only: %i[index show]
  resources :types, only: %i[index show]
  resources :orders, only: %i[index show]
  post 'pokemons/add_to_cart/:id', to: 'pokemons#add_to_cart', as: 'add_to_cart'
  delete 'pokemons/remove_from_cart/:id', to: 'pokemons#remove_from_cart', as: 'remove_from_cart'
  post 'pokemons/modify_cart_quantity', to: 'pokemons#modify_cart_quantity', as: 'modify_cart_quantity'

  get "about", to: "static_pages#about"
  get "contactus", to: "static_pages#contactus"

  # Search Results
  # get "search/results"
  get "search_results", to: "search#results"

  # Home Page
  root to: "pokemons#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/order.rb
class Order < ApplicationRecord
    has_many :pokemon_orders
    has_many :pokemons, through: :pokemon_orders

    belongs_to :user

    validates :tax, :subtotal, :status, presence: true
    validates :tax, :subtotal, numericality: { greater_than_or_equal_to: 0 }
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :pokemon_types
  has_many :types, through: :pokemon_types

  has_many :pokemon_orders
  has_many :orders, through: :pokemon_orders

  has_one_attached :pokemon_image

  validates :name, :pokedex_number, :price, :quantity, presence: true
  validates :name, :pokedex_number, uniqueness: true
  validates :pokedex_number, :quantity, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :price, :sale_percentage, numericality: true
end

app/models/pokemon_order.rb
class PokemonOrder < ApplicationRecord
  belongs_to :pokemon
  belongs_to :order

  validates :quantity, :price, presence: true
  validates :quantity, numericality: { only_integer: true }
  validates :price, numericality: { greater_than_or_equal_to: 0 }
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
  belongs_to :pokemon
  belongs_to :type
end

app/models/province.rb
class Province < ApplicationRecord
    has_many :user
    
    validates :name, :code, :pst, presence: true
    validates :name, :code, uniqueness: true
    validates :pst, numericality: { greater_than_or_equal_to: 0 }
end

app/models/static_page.rb
class StaticPage < ApplicationRecord
end

app/models/type.rb
class Type < ApplicationRecord
  has_many :pokemon_types
  has_many :pokemons, through: :pokemon_types
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders
  belongs_to :province
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  def index
    @types = Type.includes(:pokemons).all
  end

  def show
    @type = Type.find(params[:id])
    @pokemons = @type.pokemons
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonMarket</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <script src="https://js.stripe.com/v3/"></script>
  </head>

  <body>
  <header>
      
      <h1>Recipe Recipe</h1>
      <nav>
        <ul>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Types", types_path %></li>
          <li><%= link_to "Contact Us", contactus_path %></li>
          <li><%= link_to "About Us", about_path %></li>
          <% if !user_signed_in? %>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <li><%= link_to "Log In", new_session_path(:user) %></li>
          <% else %>
            <li>Hello, <%= link_to current_user.first_name, show_user_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, data: { "turbo-method": :delete } %></li>
          <% end %>
        </ul>
      </nav>
    </header>

    <div class="searchbar">
      <%= form_tag(search_results_path, method: "get") do %>
        <%= label_tag(:q, "Search for:") %>
        <%= text_field_tag(:q, params[:q]) %>

        <%= label_tag(:type, "Filter by Type:") %>
        <%= select_tag(:type, options_for_select(Type.all.collect { |c| [c.name, c.id] }, params[:type]), include_blank: true) %>

        <%= check_box_tag(:sale_percentage, 'greater_than_zero', params[:sale_percentage] == 'greater_than_zero') %>
        <%= label_tag(:sale_percentage, "Sale") %>

        <%= check_box_tag(:created_at, 'yes', params[:created_at] == 'yes') %>
        <%= label_tag(:created_at, "Recently Added") %>

        <%= check_box_tag(:updated_at, 'yes', params[:updated_at] == 'yes') %>
        <%= label_tag(:updated_at, "Recently Updated") %>

        <%= submit_tag("Search") %>
      <% end %>
    </div>

    <p>
      <details>
          <summary>Shopping Cart</summary>
          <% if @cart.empty? %>
              <p>No items in cart.</p>
          <% else %>
            <ul>
                <% @cart.each do |cart_item| %>
                  <li>
                    <%= form_tag(modify_cart_quantity_path, method: "post") do %>
                      <%= cart_item[:pokemon].name %> -
                      <%= number_field_tag(:quantity, cart_item[:qty]) %> pokemons 
                      <%= submit_tag("Update quantity") %>-
                      <%= link_to 'Remove', remove_from_cart_path(cart_item[:pokemon]), data: { "turbo-method": :delete } %>
                      <%= hidden_field_tag(:pokemon_id, cart_item[:pokemon].id) %>
                    <% end %>
                  </li>
                <% end %>
            </ul>
            <p>Subtotal: $<%= @subtotal %></p>

            <%= link_to "Checkout", checkout_review_path %> 
          <% end %>
      </details>
    </p>

    <%= yield %>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>